directories:
  output: dist_electron
  buildResources: build
appId: com.goes.checkin
productName: GOES Check-in System
copyright: Copyright © 2025
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - .env.production
extraMetadata:
  main: electron/main.cjs
mac:
  icon: build/icons/icon.icns
  category: public.app-category.business
  target:
    - dmg
    - zip
win:
  icon: build/icons/icon.ico
  target:
    - nsis
    - portable
linux:
  icon: build/icons/icon.png
  target:
    - AppImage
    - deb
  category: Office
electronVersion: 35.0.3
